### ISSUE TITLE
Error in expr[shared.genes, ] : incorrect number of dimensions

### ISSUE THREAD

**Issue by alezanalp** [dviraran/xCell#1]
I've tried to process expression matrix with TPM values from kalisto but stopped with the error:

```
[1] "Num. of genes: 0"
Error in expr[shared.genes, ] : incorrect number of dimensions
```
I also tried this file with the online version and the analysis has finished succesfully.

[Link to file on dropbox](https://www.dropbox.com/s/o5qzh7qxu8fdlso/E-MTAB-4652_kalisto_expression.txt?dl=0)

**Comment by dviraran** [comment]
Can you please send me the file you are using? this usually happens when there is no intersection between the gene names of your matrix and the gene names used by xCell. However, you are saying that it worked with online version, so I guess it is something else.

**Comment by alezanalp** [comment]
@dviraran I've just gave a link to dropbox with that file in my first post

**Comment by dviraran** [comment]
I can't reproduce your error. 

I use the following code:

expr=read.table('E-MTAB-4652_kalisto_expression.txt')
scores = xCellAnalysis(expr)

and its starts as expected. Are you reading the file differently? Note that xCell expects a matrix or a data.frame.

**Comment by alezanalp** [comment]
Ok, now I get it, thank you.

Please add this to the Usage section because you have their only:

> library(xCell)
> xCellAnalysis(exprMatrix)

and it is not obvious that I may first load the matrix in the environment myself and the function don't do it itself. Or may be it is better to add this line in you code exactly?

> expr=read.table('E-MTAB-4652_kalisto_expression.txt')

**Comment by dviraran** [comment]
Updated. Thanks!
