### ISSUE TITLE
table to exprMatrix

### ISSUE THREAD

**Issue by pbrazda** [dviraran/xCell#20]
**Hello,**

**Sorry about the basic question:
I tried to load the _iris_u133a_expr.txt_ example file, but failed. Where did I go wrong?**

`library(xCell)`
`library(data.table)`
`iris <- fread("iris_u133a_expr.txt")`
`exprMatrix = read.table(iris,header=TRUE,row.names=1, as.is=TRUE)`
`xCellAnalysis(exprMatrix)`

**for** `exprMatrix = read.table(iris,header=TRUE,row.names=1, as.is=TRUE)`
**I get:**

> Error in read.table(iris, header = TRUE, row.names = 1, as.is = TRUE) : 
>   'file' must be a character string or connection

**Any suggestions?**
**Thank you!**

**Peter**

**Comment by dviraran** [comment]
Hi,

Try as.matrix(exprMatrix)

**Comment by pbrazda** [comment]
It worked. Thank you!
