### ISSUE TITLE
upload on bioconda / release latest package version

### ISSUE THREAD

**Issue by grst** [dviraran/xCell#22]
Hi @dviraran, 

I would like to create a [bioconda](https://github.com/bioconda/bioconda-recipes) package for xCell, so that all dependencies for [immunedeconv](https://github.com/grst/immunedeconv) are available on bioconda. 

* Is that ok for you?
* Could you please create a release for the current version that can be used for the bioconda package?

Best regards, 
Gregor

**Comment by grst** [comment]
@dviraran ?

**Comment by dviraran** [comment]
Sorry, missed this comment. 

Sure. I just created a release (for bioconda).

**Comment by grst** [comment]
The package got just approved on bioconda. 

xCell can now be installed via 
```bash
conda install -c bioconda -c conda-forge r-xcell
```

**Comment by dviraran** [comment]
Awesome! thanks!
