### ISSUE TITLE
Small bug in R/xCell.R related to spill

### ISSUE THREAD

**Issue by aeolianine** [dviraran/xCell#30]
Hi, 

If you define **novel cell types** and corresponding spill matrices, and use the main script xCellAnalysis(), an error is generated ('ERROR - not all cell types listed are available'). That's because of line 60 in R/xCell.R. Regardless of what spill you specified, line 60 checks the new cell types against the internally stored spill matrices, and some will of course be missing.

Current:
Line 60: A = intersect(cell.types.use,rownames(xCell.data$spill$K))

Suggestion:
Line 60: A = intersect(cell.types.use,rownames(spill$K))

Cheers,
aeolianine

**Comment by dviraran** [comment]
Thanks! fixed it.
