### ISSUE TITLE
install package on Windows R

### ISSUE THREAD

**Issue by biozhao** [dviraran/xCell#34]
Hi,  I try to install from Github using devtools and I get these error messages:
> devtools::install_github('dviraran/xCell')
Downloading GitHub repo dviraran/xCell@master
Error in utils::download.file(url, path, method = download_method(), quiet = quiet,  : 
  cant not open URL'https://api.github.com/repos/dviraran/xCell/tarball/master'

I change the language ,but there is nothing change
> sessionInfo()
R version 3.5.2 (2018-12-20)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

>Sys.setlocale(category = "LC_ALL", locale = "us")

Would you help me work out how to fix the problem? thank you very much!

**Comment by dviraran** [comment]
Hi,

Please try installing the new SingleR version - https://bioconductor.org/packages/devel/bioc/html/SingleR.html

Best,
Dvir

**Comment by biozhao** [comment]
thank you, i also got it on bioconda
https://anaconda.org/grst/r-xcell
