### ISSUE TITLE
Gene alias used in xCell.

### ISSUE THREAD

**Issue by RuiLi1993** [dviraran/xCell#36]
Hi,
Recently i found that some of the gene symbols used by xCell had been outdated. For example, 	AIM1 and ACP3, known as CRYBG1 and ACPP now in HGNC database. Because i always annotate my datasets using latest HGNC gene symbols, is it possible that these alias would affect the results what xCell was supposed to provide? 
Thanks.

**Comment by dviraran** [comment]
Hi,

Thanks for the information. Regarding those two gene - I only see them in one signature (for aDC), so the effect will be very limited. However, you right that this is a problem.

At least in theory, you should attempt to match as many genes as possible from xCell.data$genes.

Best,
Dvir

**Comment by RuiLi1993** [comment]
Thanks for your kindly reply, Dviraran.
