### ISSUE TITLE
Question regarding comparing enrichment scores for a cell type across samples

### ISSUE THREAD

**Issue by cwang131** [dviraran/xCell#47]
Hi,
Thank you for sharing this great tool along with detailed guidelines for running the tool and interpreting the results!
I have a question regarding comparing the enrichment scores for a cell type across samples. If the samples fall into two groups, I wonder if it would be appropriate to apply a statistical test to the enrichment score to determine if samples in one group have significantly higher enrichment scores than those in the other group for a given cell type. I'd appreciate any of your suggestions. Thank you!

**Comment by dviraran** [comment]
Thank you for your kind words. 

Yes, of course. I usually use a non-parametric test, such as Wilcoxon rank sum test. You can take a look at a book chapter I wrote on how to interpret xCell results - https://link.springer.com/protocol/10.1007/978-1-0716-0327-7_19

Best,
Dvir

**Comment by cwang131** [comment]
Thank you for the prompt response! I appreciate it.
