### ISSUE TITLE
The xCell scores I get for TCGA BRCA samples are different from what is in the paper

### ISSUE THREAD

**Issue by murphycj** [dviraran/xCell#5]
Very interesting paper! Before I try to apply it to my own data, I tried to reproduce some of the data (the TCGA BRCA dataset) in the paper to make sure I’ am using it correctly. But the xCell normalized scores I get do not match what I see in the paper. Here are my steps:

1. Download the datasets.

For the TCGA FPKM measurements, from https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM1536837 I downloaded the following file: GSM1536837_01_27_15_TCGA_20.Illumina.tumor_Rsubread_FPKM.txt.gz

For what TCGA samples in the above file were BRCA cancer subtype I downloaded GSE62944_01_27_15_TCGA_20_CancerType_Samples.txt.gz from https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE62944

I download supplementary table 4 from http://biorxiv.org/content/early/2017/03/08/114165.figures-only

2. My code:
```

library(data.table)
library(xCell)

tcga.fpkm <- fread("GSM1536837_06_01_15_TCGA_24.tumor_Rsubread_FPKM.txt",sep="\t",header=T,check.names=F)
samples <- read.table("GSE62944_01_27_15_TCGA_20_CancerType_Samples.txt",sep="\t")
samples <- samples[samples[,2]=="BRCA",]
brca.fpkm <- data.frame(tcga.fpkm[,c("V1",as.character(samples[,1])),with=F],check.names=F)
row.names(brca.fpkm) <- brca.fpkm[,"V1"]
brca.fpkm <- brca.fpkm[,!(names(brca.fpkm) %in% c("V1"))]

r <- xCellAnalysis(brca.fpkm)

pdf("TCGA.BRCA.pdf",width=16,height=6)
par(mar=c(14,3,3,3))
boxplot(t(r),las=2,pch=".")
dev.off()


paper.data <- read.table("114165-5.txt",sep="\t",header=T,row.names=1)
paper.data.brca <- paper.data[,grep("BRCA",colnames(paper.data))]

pdf("TCGA.BRCA.paper.pdf",width=16,height=6)
par(mar=c(14,3,3,3))
boxplot(t(paper.data.brca),las=2,pch=".")
dev.off()

```

Attached are the two bar charts I get. Is there some normalizations step I’ am missing?

[TCGA.BRCA.paper.pdf](https://github.com/dviraran/xCell/files/1049242/TCGA.BRCA.paper.pdf)
[TCGA.BRCA.pdf](https://github.com/dviraran/xCell/files/1049241/TCGA.BRCA.pdf)

**Comment by dviraran** [comment]
Are you using version 1.0 or version 1.1? 
The code here has been updated to v1.1 just a few days ago, but the bioRxiv paper has not been updated yet. There are many differences in this version, hopefully better now...

Another reasons for discrepancies is that I run all the TCGA samples together, not just the BRCA samples. Because xCell uses the minimal values across all the sample, it is preferable to use all data together. The more heterogenous the data is the better the scores are expected to be.

**Comment by murphycj** [comment]
I' am using version 1.1. I downloaded the code from here, and it says 1.1 after running ?xCell in R. I ran it again using all TCGA samples. Here is my code:

```
library(data.table)
library(xCell)

tcga.fpkm <- fread("GSM1536837_06_01_15_TCGA_24.tumor_Rsubread_FPKM.txt",sep="\t",header=T,check.names=F)
tcga.fpkm <- as.data.frame(tcga.fpkm)
row.names(tcga.fpkm) <- tcga.fpkm[,"V1"]
tcga.fpkm <- tcga.fpkm[,!(names(tcga.fpkm) %in% c("V1"))]

r <- xCellAnalysis(tcga.fpkm)

samples <- read.table("GSE62944_01_27_15_TCGA_20_CancerType_Samples.txt",sep="\t")
samples <- samples[samples[,2]=="BRCA",]
r.brca <- r[,as.character(samples[,1])]

pdf("TCGAall.BRCA.pdf",width=16,height=6)
par(mar=c(14,3,3,3))
boxplot(t(r.brca),las=2,pch=".")
dev.off()
```
[TCGAall.BRCA.pdf](https://github.com/dviraran/xCell/files/1059427/TCGAall.BRCA.pdf)

**Comment by dviraran** [comment]
ok, again. The manuscript in bioRxiv (including SuppTable4) is not yet updated. In the new version I used the data from http://xena.ucsc.edu/public-hubs/. The expression there was quantified using Kallisto and RSEM, opposed to the FPKM data. For BRCA the results I'm getting are a bit different, but I think that as a whole they are generally similar. Your data seems cleaner, which makes me wonder wether the Rsubread/FPKM data is of better quality.
 
[TCGAall.BRCA.pdf](https://github.com/dviraran/xCell/files/1059449/TCGAall.BRCA.pdf)

**Comment by murphycj** [comment]
Ok. I reinstalled the package from source by downloading the 1.1 branch. I got basically the same thing. I'll take a Loog at that link you sent.
[TCGAall.BRCA.pdf](https://github.com/dviraran/xCell/files/1059550/TCGAall.BRCA.pdf)
