### ISSUE TITLE
Batch effects in input data and reliability of applying xCell to non-human species

### ISSUE THREAD

**Issue by cwang131** [dviraran/xCell#51]
Hi, 

I've been trying to apply xCell to some data that has batch effect issue across groups of interest. I wonder if aggregated data containing those from different batches without batch correction could be used as input for xCell scoring and if downstream comparison of a cell-type score across groups could still be reliable. The manuscript touched briefly on the robustness against batch effect in the discussion. I'd appreciate your insights.

In addition, related to a previous issue (https://github.com/dviraran/xCell/issues/26), I wonder if xCell could be applied to non-human species, such as rats, mice, and ferrets. 

Thank you!

**Comment by dviraran** [comment]
Hi,

Regarding batch effects - xCell uses gene expression ranks and not the levels themselves. This means that different normalization and batch effect corrections will have little effect on the xCell analysis.

Regarding non-human, I don't recommend it, it is not trained for non-human species. However, I know that some groups got ok results with the current version of xCell in other primates and mice.  

Best,
Dvir

**Comment by cwang131** [comment]
Thank you very much for your help! I really appreciate it.
