### ISSUE TITLE
How do I see the gene names contained in each cell type?

### ISSUE THREAD

**Issue by Gaodelike** [dviraran/xCell#55]
As the question shows, I got results from xcellanalysis, but how should I see which genes are enriched under each cell type?
Hope to get your reply, thank you!

**Comment by dviraran** [comment]
Hi,

xCell doesn't output such a thing. xCell only outputs enrichment scores for cell types, not genes. You can identify genes that their expression is correlated with enrichment scores.

Best,
Dvir

**Comment by Gaodelike** [comment]
> Hi,
> 
> xCell doesn't output such a thing. xCell only outputs enrichment scores for cell types, not genes. You can identify genes that their expression is correlated with enrichment scores.
> 
> Best,
> Dvir

Thanks！
