### ISSUE TITLE
Use xCell signatures + custom ones for other cell types

### ISSUE THREAD

**Issue by Lisa-Salhi** [dviraran/xCell#56]
Hello,

Is it possible to run xCell with a subset of your signatures (11 cell types, 121 signatures) and add 2 cell types with custom gene signatures?
I tried to copy paste a subset of your signatures in a gmt file and add a line per added custom population, but it considers each row of your signatures as different cell populations, and does not do the average of the scores. I also tried to play with the `cell.types.use` parameter, but I got errors. How can I manage the several xCell signatures per population + my 2 added signatures for 2 more populations?

Best regards,

Lisa

**Comment by dviraran** [comment]
Hi,

Unfortunately, in the current version, you can't add signatures of your own. As you said can use `cell.types.use` to run the analysis for a subset of cells, which can improve the results. See https://europepmc.org/article/med/32124326 for example.

Best,
Dvir

**Comment by Lisa-Salhi** [comment]
Ok, thanks a lot for your quick reply.
Best,
Lisa
