### ISSUE TITLE
Minimum number of genes required

### ISSUE THREAD

**Issue by liscruk** [dviraran/xCell#72]
Hi,

I was recommended xCell for Nanostring analysis, however, the panels only measure 700 genes.
So obviously, this will trigger the ERROR of not enough genes measured. 
Could you elaborate on why this is necessary and if you expected issues if I circumvent this error?

Thanks!

See the relevant code here:

https://github.com/dviraran/xCell/blob/7339410585bcccb2c2ceec2af47c8bcb646b42b2/R/xCell.R#L107-L110

**Comment by dviraran** [comment]
xCell uses signatures and rankings. If the genes in the signature are not present in the input data, it won't be able to calculate scores. Also, xCell was trained with a list of 10K genes, and all parameters are optimal when all those 10K are available. I would not recommend xCell for nanostring at the current moment, I hope to share soon a method that will allow to do that.

Best,
Dvir
