### ISSUE TITLE
Error in processing xcell analysis

### ISSUE THREAD

**Issue by tjer1ryom** [dviraran/xCell#78]
Hi,
I have been interested in for immune infiltration analysis for a while and impressed by xcell.But many RNA expression dataset i collected from GEO cannot perform xcell and it replies like 

>    xcell<-xCellAnalysis(GSE77167,rnaseq=F)
+   [1] "Num. of genes: 0"
+   [1] "ERROR: not enough genes"
+   Error in return - 1 : non-numeric argument to binary operator

I have checked the normalization process and each dataset contains enough gene(~20000).I cannot firure out why this happened and it have bothered me some days:( 
I am dull, please tell me!

**Comment by dviraran** [comment]
[1] "Num. of genes: 0"

This means that the rownames in your data are not gene symbols. xCell assumes that you are using gene symbols and not some other gene ids.

Best,
Dvir

**Comment by tjer1ryom** [comment]
Thank for your reply!
According to your prompt, I rechecked the column of gene symbols (rownames) and confirmed that they indeed represent genes. However, it includes pseudogenes and mitochondrial genes, etc. It may be a problem.
Additionally, I attempted to integrate the gene expression data into another dataset and found that it can be analyzed normally, which confuses me. The data I am analyzing has undergone log2 transformation and limma differential analysis. I am not sure if this has an impact, or if I should analyze the original data.
I've uploaded the gene expression matrix file. If you could spare a moment to see where something might have gone wrong, I'd be very grateful!
Yours,
Tj
[GSE77167_norm_exp_data.txt](https://github.com/dviraran/xCell/files/13619673/GSE77167_norm_exp_data.txt)

**Comment by tjer1ryom** [comment]
The same problem also occurs here, only endured background correction, rma normalizaion and gene expression index calculation of probe intensities.
Really want to konw the cause and the solution, pls QAQ
Sorry for my disturbance.
[GSE122626_norm_exp_data.txt](https://github.com/dviraran/xCell/files/13626566/GSE122626_norm_exp_data.txt)

**Comment by dviraran** [comment]
For some reason you have an extra space in all the gene names. rownames(a) = gsub(' ','',rownames(a)) should fix that...

**Comment by tjer1ryom** [comment]
Apologize for my silence for weeks, and thank for your reply from the bottom of my heart!
However, there's another issue emerged:
+   xcell<-xCellAnalysis(GSE75050.norm, rnaseq=F)
+   [1] "Num. of genes: 10514"
+   Error: useNames = NA is defunct. Instead, specify either useNames = TRUE or useNames = FALSE.

The same data can be analysied in the web xcell, so i wonder what's wrong and how can i figure it out. (i have updated all packages and changed network enviroment)
Thanks again!
Yours,
Tj

**Comment by dviraran** [comment]
It's an issue with the matrixStats package. It made havoc throughout many packages. You need to upgrade your BioConductor and all associated with packages.

Best,
Dvir

**Comment by tjer1ryom** [comment]
I conquer it! tooooooooooo much appreciation for you!!! 
Wish you a wonderful 2024! :)
Yours,
Tj

**Comment by tdfy** [comment]
recently got this error, perhaps assocaited with matrixStats 1.5.0 ?

```
[1] "Num. of genes: 10795"
Error in rowVars(x, rows = rows, cols = cols, na.rm = na.rm, refine = refine,  : 
  Argument 'useNames' must be either TRUE or FALSE
```

**Comment by dviraran** [comment]
Hi,

This version is xCell is not supported anymore. Please try out our new [xCell 2.0](https://github.com/AlmogAngel/xCell2).

Best,
Dvir
